// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	kgo "github.com/twmb/franz-go/pkg/kgo"
)

// MockDLQPublisher is an autogenerated mock type for the DLQPublisher type
type MockDLQPublisher struct {
	mock.Mock
}

type MockDLQPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDLQPublisher) EXPECT() *MockDLQPublisher_Expecter {
	return &MockDLQPublisher_Expecter{mock: &_m.Mock}
}

// PublishDLQ provides a mock function with given fields: record
func (_m *MockDLQPublisher) PublishDLQ(record *kgo.Record) {
	_m.Called(record)
}

// MockDLQPublisher_PublishDLQ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishDLQ'
type MockDLQPublisher_PublishDLQ_Call struct {
	*mock.Call
}

// PublishDLQ is a helper method to define mock.On call
//   - record *kgo.Record
func (_e *MockDLQPublisher_Expecter) PublishDLQ(record interface{}) *MockDLQPublisher_PublishDLQ_Call {
	return &MockDLQPublisher_PublishDLQ_Call{Call: _e.mock.On("PublishDLQ", record)}
}

func (_c *MockDLQPublisher_PublishDLQ_Call) Run(run func(record *kgo.Record)) *MockDLQPublisher_PublishDLQ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*kgo.Record))
	})
	return _c
}

func (_c *MockDLQPublisher_PublishDLQ_Call) Return() *MockDLQPublisher_PublishDLQ_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDLQPublisher_PublishDLQ_Call) RunAndReturn(run func(*kgo.Record)) *MockDLQPublisher_PublishDLQ_Call {
	_c.Run(run)
	return _c
}

// NewMockDLQPublisher creates a new instance of MockDLQPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDLQPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDLQPublisher {
	mock := &MockDLQPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
