// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	clients "github.com/MathTrail/mentor-api/internal/clients"

	mock "github.com/stretchr/testify/mock"
)

// MockFeedbackClient is an autogenerated mock type for the FeedbackClient type
type MockFeedbackClient struct {
	mock.Mock
}

type MockFeedbackClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeedbackClient) EXPECT() *MockFeedbackClient_Expecter {
	return &MockFeedbackClient_Expecter{mock: &_m.Mock}
}

// AnalyzeFeedback provides a mock function with given fields: ctx, message
func (_m *MockFeedbackClient) AnalyzeFeedback(ctx context.Context, message string) (*clients.StrategyResult, error) {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for AnalyzeFeedback")
	}

	var r0 *clients.StrategyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*clients.StrategyResult, error)); ok {
		return rf(ctx, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *clients.StrategyResult); ok {
		r0 = rf(ctx, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients.StrategyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFeedbackClient_AnalyzeFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnalyzeFeedback'
type MockFeedbackClient_AnalyzeFeedback_Call struct {
	*mock.Call
}

// AnalyzeFeedback is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
func (_e *MockFeedbackClient_Expecter) AnalyzeFeedback(ctx interface{}, message interface{}) *MockFeedbackClient_AnalyzeFeedback_Call {
	return &MockFeedbackClient_AnalyzeFeedback_Call{Call: _e.mock.On("AnalyzeFeedback", ctx, message)}
}

func (_c *MockFeedbackClient_AnalyzeFeedback_Call) Run(run func(ctx context.Context, message string)) *MockFeedbackClient_AnalyzeFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFeedbackClient_AnalyzeFeedback_Call) Return(_a0 *clients.StrategyResult, _a1 error) *MockFeedbackClient_AnalyzeFeedback_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFeedbackClient_AnalyzeFeedback_Call) RunAndReturn(run func(context.Context, string) (*clients.StrategyResult, error)) *MockFeedbackClient_AnalyzeFeedback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFeedbackClient creates a new instance of MockFeedbackClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedbackClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedbackClient {
	mock := &MockFeedbackClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
