// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	clients "github.com/MathTrail/mentor-api/internal/clients"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProfileClient is an autogenerated mock type for the ProfileClient type
type MockProfileClient struct {
	mock.Mock
}

type MockProfileClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileClient) EXPECT() *MockProfileClient_Expecter {
	return &MockProfileClient_Expecter{mock: &_m.Mock}
}

// GetProfile provides a mock function with given fields: ctx, studentID
func (_m *MockProfileClient) GetProfile(ctx context.Context, studentID uuid.UUID) (*clients.Profile, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *clients.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*clients.Profile, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *clients.Profile); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProfileClient_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockProfileClient_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - studentID uuid.UUID
func (_e *MockProfileClient_Expecter) GetProfile(ctx interface{}, studentID interface{}) *MockProfileClient_GetProfile_Call {
	return &MockProfileClient_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, studentID)}
}

func (_c *MockProfileClient_GetProfile_Call) Run(run func(ctx context.Context, studentID uuid.UUID)) *MockProfileClient_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProfileClient_GetProfile_Call) Return(_a0 *clients.Profile, _a1 error) *MockProfileClient_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProfileClient_GetProfile_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*clients.Profile, error)) *MockProfileClient_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProfileClient creates a new instance of MockProfileClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileClient {
	mock := &MockProfileClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
