apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: mentor-api

build:
  local:
    push: true
    tryImportMissing: false
  tagPolicy:
    inputDigest: {}
  insecureRegistries:
    - k3d-mathtrail-registry:5000
  artifacts:
    - image: mentor-api
      custom:
        buildCommand: just build-push-image
        dependencies:
          dockerfile:
            path: Dockerfile

deploy:
  statusCheck: true
  statusCheckDeadlineSeconds: 150
  helm:
    releases:
      - name: mentor-api
        chartPath: infra/helm/mentor-api
        namespace: mathtrail
        createNamespace: true
        wait: true
        valuesFiles:
          - infra/helm/mentor-api/values.yaml
          - infra/helm/values-dev.yaml
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_mentor_api}}"
          image.tag: "{{.IMAGE_TAG_mentor_api}}"

portForward:
  - resourceType: service
    resourceName: mentor-api
    namespace: mathtrail
    port: 8080
    localPort: 8080

---
apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: mentor-deps

build:
  artifacts: []

manifests:
  rawYaml:
    - |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: mentor-deps-anchor
        namespace: mathtrail
      data:
        status: "infrastructure-ready"

deploy:
  kubectl: {}

requires:
  - git:
      repo: https://github.com/MathTrail/infra-local
      path: skaffold.yaml
      ref: main # todo: specify concrete version
    activeProfiles:
      - name: postgres

---
apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: mentor-load-tests

build:
  artifacts: []

deploy:
  helm:
    releases:
      - name: mentor-api-load-test
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: k6-test-runner
        namespace: mathtrail
        createNamespace: true
        setValues:
          baseUrl: http://mentor-api.mathtrail.svc.cluster.local:8080
          parallelism: 1
        setFiles:
          loadTestScript: tests/load/dist/bundle.js
