apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: mentor-api

build:
  local:
    push: true
    tryImportMissing: false
  insecureRegistries:
    - k3d-mathtrail-registry.localhost:5050
  artifacts:
    - image: mentor-api
      custom:
        buildCommand: just build-push-image
        dependencies:
          dockerfile:
            path: Dockerfile

deploy:
  helm:
    releases:
      - name: mentor-api
        chartPath: infra/helm/mentor-api
        namespace: mathtrail
        createNamespace: true
        wait: true
        valuesFiles:
          - infra/helm/mentor-api/values.yaml
          - infra/helm/values-dev.yaml
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_mentor_api}}"
          image.tag: "{{.IMAGE_TAG_mentor_api}}"

portForward:
  - resourceType: service
    resourceName: mentor-api
    namespace: mathtrail
    port: 8080
    localPort: 8080
