package feedback

import (
	"context"
	"errors"
	"strings"
	"testing"
	"time"

	pgmocks "github.com/MathTrail/mentor-api/internal/infra/postgres/mocks"
	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
)

const (
	unexpectedErrorFmt = "unexpected error: %v"
	expectedErrNilFmt  = "expected error, got nil"
)

// --- Save tests ---

func TestSaveSuccess(t *testing.T) {
	now := time.Now().UTC().Truncate(time.Second)

	db := pgmocks.NewMockDB(t)
	db.EXPECT().Query(
		mock.Anything, mock.Anything,
		mock.Anything, mock.Anything, mock.Anything,
		mock.Anything, mock.Anything, mock.Anything,
	).Return([]map[string]any{
		{"created_at": now.Format(time.RFC3339)},
	}, nil)

	repo := NewRepository(db)
	f := &Feedback{
		StudentID:           uuid.New(),
		Message:             "test message",
		PerceivedDifficulty: "ok",
		StrategySnapshot:    []byte(`{}`),
	}

	if err := repo.Save(context.Background(), f); err != nil {
		t.Fatalf("Save error: %v", err)
	}
	// ID is generated by uuid.NewV7() inside Save — verify it is non-zero.
	if f.ID == uuid.Nil {
		t.Error("ID should be non-zero after Save")
	}
	if f.CreatedAt.IsZero() {
		t.Error("CreatedAt should be non-zero after Save")
	}
}

func TestSaveDBError(t *testing.T) {
	dbErr := errors.New("connection refused")

	db := pgmocks.NewMockDB(t)
	db.EXPECT().Query(
		mock.Anything, mock.Anything,
		mock.Anything, mock.Anything, mock.Anything,
		mock.Anything, mock.Anything, mock.Anything,
	).Return(nil, dbErr)

	repo := NewRepository(db)
	f := &Feedback{StudentID: uuid.New(), Message: "test"}

	err := repo.Save(context.Background(), f)
	if err == nil {
		t.Fatal(expectedErrNilFmt)
	}
	if !errors.Is(err, dbErr) {
		t.Errorf("error chain: got %v, want to contain %v", err, dbErr)
	}
}

func TestSaveEmptyRows(t *testing.T) {
	db := pgmocks.NewMockDB(t)
	db.EXPECT().Query(
		mock.Anything, mock.Anything,
		mock.Anything, mock.Anything, mock.Anything,
		mock.Anything, mock.Anything, mock.Anything,
	).Return([]map[string]any{}, nil)

	repo := NewRepository(db)
	f := &Feedback{StudentID: uuid.New(), Message: "test"}

	err := repo.Save(context.Background(), f)
	if err == nil {
		t.Fatal("expected error on empty rows, got nil")
	}
	if !strings.Contains(err.Error(), "no rows") {
		t.Errorf("error message: got %q, want to contain 'no rows'", err.Error())
	}
}

// --- GetLatestByStudent tests ---

func TestGetLatestByStudentSuccess(t *testing.T) {
	id1, id2 := uuid.New(), uuid.New()
	studentID := uuid.New()
	now := time.Now().UTC()

	db := pgmocks.NewMockDB(t)
	db.EXPECT().Query(mock.Anything, mock.Anything, mock.Anything, mock.Anything).
		Return([]map[string]any{
			{
				"id":                   id1.String(),
				"student_id":           studentID.String(),
				"task_id":              "task-1",
				"message":              "first",
				"perceived_difficulty": "ok",
				"strategy_snapshot":    `{}`,
				"created_at":           now.Format(time.RFC3339),
			},
			{
				"id":                   id2.String(),
				"student_id":           studentID.String(),
				"task_id":              "task-2",
				"message":              "second",
				"perceived_difficulty": "hard",
				"strategy_snapshot":    `{}`,
				"created_at":           now.Add(-time.Minute).Format(time.RFC3339),
			},
		}, nil)

	repo := NewRepository(db)
	results, err := repo.GetLatestByStudent(context.Background(), studentID, 10)
	if err != nil {
		t.Fatalf(unexpectedErrorFmt, err)
	}
	if len(results) != 2 {
		t.Errorf("len: got %d, want 2", len(results))
	}
	if results[0].ID != id1 {
		t.Errorf("results[0].ID: got %v, want %v", results[0].ID, id1)
	}
	if results[1].ID != id2 {
		t.Errorf("results[1].ID: got %v, want %v", results[1].ID, id2)
	}
}

func TestGetLatestByStudentEmpty(t *testing.T) {
	db := pgmocks.NewMockDB(t)
	db.EXPECT().Query(mock.Anything, mock.Anything, mock.Anything, mock.Anything).
		Return([]map[string]any{}, nil)

	repo := NewRepository(db)
	results, err := repo.GetLatestByStudent(context.Background(), uuid.New(), 10)
	if err != nil {
		t.Fatalf(unexpectedErrorFmt, err)
	}
	if len(results) != 0 {
		t.Errorf("expected empty slice, got len %d", len(results))
	}
}

func TestGetLatestByStudentDBError(t *testing.T) {
	dbErr := errors.New("timeout")

	db := pgmocks.NewMockDB(t)
	db.EXPECT().Query(mock.Anything, mock.Anything, mock.Anything, mock.Anything).
		Return(nil, dbErr)

	repo := NewRepository(db)
	_, err := repo.GetLatestByStudent(context.Background(), uuid.New(), 5)
	if err == nil {
		t.Fatal(expectedErrNilFmt)
	}
	if !errors.Is(err, dbErr) {
		t.Errorf("error chain: got %v, want to contain %v", err, dbErr)
	}
}
