{{- if .Values.vaultConfig.enabled }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineConfig
metadata:
  name: {{ .Values.vaultConfig.db.connectionName }}
  namespace: vault-config-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  authentication:
    path: kubernetes
    role: vco-admin
    serviceAccount:
      name: controller-manager
  connection:
    address: http://vault.vault.svc.cluster.local:8200 # NOSONAR: internal cluster traffic, TLS handled at mesh level
    tLSConfig:
      skipVerify: true
  path: database
  pluginName: postgresql-database-plugin
  allowedRoles:
    - {{ .Values.vaultConfig.db.roleName }}
  connectionURL: "postgresql://{{`{{username}}`}}:{{`{{password}}`}}@postgres-postgresql.mathtrail.svc.cluster.local:5432/{{ .Values.vaultConfig.db.database }}?sslmode=disable"
  username: postgres
  rootCredentials:
    secret:
      name: postgres-root-credentials
    passwordKey: password
{{- end }}
