{{- if .Values.vaultConfig.enabled }}
{{- $pgSecret := lookup "v1" "Secret" .Release.Namespace "postgres-postgresql" -}}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-root-credentials-{{ .Release.Namespace }}
  namespace: vault-config-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  {{- if $pgSecret }}
  password: {{ index $pgSecret.data "postgres-password" }}
  {{- else }}
  password: {{ "" | b64enc }}
  {{- end }}
{{- end }}
