// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	roadmap "github.com/MathTrail/mentor-api/internal/domain/roadmap"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetRecommendations provides a mock function with given fields: ctx, studentID
func (_m *MockService) GetRecommendations(ctx context.Context, studentID uuid.UUID) (*roadmap.Recommendation, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetRecommendations")
	}

	var r0 *roadmap.Recommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*roadmap.Recommendation, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *roadmap.Recommendation); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*roadmap.Recommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecommendations'
type MockService_GetRecommendations_Call struct {
	*mock.Call
}

// GetRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - studentID uuid.UUID
func (_e *MockService_Expecter) GetRecommendations(ctx interface{}, studentID interface{}) *MockService_GetRecommendations_Call {
	return &MockService_GetRecommendations_Call{Call: _e.mock.On("GetRecommendations", ctx, studentID)}
}

func (_c *MockService_GetRecommendations_Call) Run(run func(ctx context.Context, studentID uuid.UUID)) *MockService_GetRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_GetRecommendations_Call) Return(_a0 *roadmap.Recommendation, _a1 error) *MockService_GetRecommendations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetRecommendations_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*roadmap.Recommendation, error)) *MockService_GetRecommendations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
