// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDB is an autogenerated mock type for the DB type
type MockDB struct {
	mock.Mock
}

type MockDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDB) EXPECT() *MockDB_Expecter {
	return &MockDB_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, sql, params
func (_m *MockDB) Exec(ctx context.Context, sql string, params ...any) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) error); ok {
		r0 = rf(ctx, sql, params...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDB_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockDB_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - params ...any
func (_e *MockDB_Expecter) Exec(ctx interface{}, sql interface{}, params ...interface{}) *MockDB_Exec_Call {
	return &MockDB_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, params...)...)}
}

func (_c *MockDB_Exec_Call) Run(run func(ctx context.Context, sql string, params ...any)) *MockDB_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDB_Exec_Call) Return(_a0 error) *MockDB_Exec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_Exec_Call) RunAndReturn(run func(context.Context, string, ...any) error) *MockDB_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockDB) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDB_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockDB_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDB_Expecter) Ping(ctx interface{}) *MockDB_Ping_Call {
	return &MockDB_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockDB_Ping_Call) Run(run func(ctx context.Context)) *MockDB_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDB_Ping_Call) Return(_a0 error) *MockDB_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_Ping_Call) RunAndReturn(run func(context.Context) error) *MockDB_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, sql, params
func (_m *MockDB) Query(ctx context.Context, sql string, params ...any) ([]map[string]any, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []map[string]any
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) ([]map[string]any, error)); ok {
		return rf(ctx, sql, params...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) []map[string]any); ok {
		r0 = rf(ctx, sql, params...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]any)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, sql, params...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockDB_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - params ...any
func (_e *MockDB_Expecter) Query(ctx interface{}, sql interface{}, params ...interface{}) *MockDB_Query_Call {
	return &MockDB_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, sql}, params...)...)}
}

func (_c *MockDB_Query_Call) Run(run func(ctx context.Context, sql string, params ...any)) *MockDB_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDB_Query_Call) Return(_a0 []map[string]any, _a1 error) *MockDB_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_Query_Call) RunAndReturn(run func(context.Context, string, ...any) ([]map[string]any, error)) *MockDB_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDB creates a new instance of MockDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDB {
	mock := &MockDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
