// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/feedback": {
            "post": {
                "description": "Process student feedback about task difficulty.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "feedback"
                ],
                "summary": "Submit student feedback",
                "parameters": [
                    {
                        "description": "Feedback request",
                        "name": "feedback",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/feedback.FeedbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/feedback.StrategyUpdate"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/feedback.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/feedback.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "feedback.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "feedback.FeedbackRequest": {
            "type": "object",
            "required": [
                "message",
                "student_id",
                "task_id"
            ],
            "properties": {
                "message": {
                    "type": "string",
                    "maxLength": 5000
                },
                "student_id": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "feedback.StrategyUpdate": {
            "type": "object",
            "properties": {
                "difficulty_adjustment": {
                    "type": "number"
                },
                "sentiment": {
                    "type": "string"
                },
                "strategy_snapshot": {
                    "type": "object",
                    "additionalProperties": true
                },
                "student_id": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "topic_weights": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Mentor API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
