// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	feedback "github.com/MathTrail/mentor-api/internal/domain/feedback"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetLatestByStudent provides a mock function with given fields: ctx, studentID, limit
func (_m *MockRepository) GetLatestByStudent(ctx context.Context, studentID uuid.UUID, limit int) ([]feedback.Feedback, error) {
	ret := _m.Called(ctx, studentID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestByStudent")
	}

	var r0 []feedback.Feedback
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]feedback.Feedback, error)); ok {
		return rf(ctx, studentID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []feedback.Feedback); ok {
		r0 = rf(ctx, studentID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]feedback.Feedback)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, studentID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetLatestByStudent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestByStudent'
type MockRepository_GetLatestByStudent_Call struct {
	*mock.Call
}

// GetLatestByStudent is a helper method to define mock.On call
//   - ctx context.Context
//   - studentID uuid.UUID
//   - limit int
func (_e *MockRepository_Expecter) GetLatestByStudent(ctx interface{}, studentID interface{}, limit interface{}) *MockRepository_GetLatestByStudent_Call {
	return &MockRepository_GetLatestByStudent_Call{Call: _e.mock.On("GetLatestByStudent", ctx, studentID, limit)}
}

func (_c *MockRepository_GetLatestByStudent_Call) Run(run func(ctx context.Context, studentID uuid.UUID, limit int)) *MockRepository_GetLatestByStudent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockRepository_GetLatestByStudent_Call) Return(_a0 []feedback.Feedback, _a1 error) *MockRepository_GetLatestByStudent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetLatestByStudent_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) ([]feedback.Feedback, error)) *MockRepository_GetLatestByStudent_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) Save(ctx context.Context, _a1 *feedback.Feedback) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *feedback.Feedback) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *feedback.Feedback
func (_e *MockRepository_Expecter) Save(ctx interface{}, _a1 interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save", ctx, _a1)}
}

func (_c *MockRepository_Save_Call) Run(run func(ctx context.Context, _a1 *feedback.Feedback)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*feedback.Feedback))
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(_a0 error) *MockRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(context.Context, *feedback.Feedback) error) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
