// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	feedback "github.com/MathTrail/mentor-api/internal/domain/feedback"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ProcessFeedback provides a mock function with given fields: ctx, req
func (_m *MockService) ProcessFeedback(ctx context.Context, req *feedback.FeedbackRequest) (*feedback.StrategyUpdate, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ProcessFeedback")
	}

	var r0 *feedback.StrategyUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *feedback.FeedbackRequest) (*feedback.StrategyUpdate, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *feedback.FeedbackRequest) *feedback.StrategyUpdate); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feedback.StrategyUpdate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *feedback.FeedbackRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ProcessFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessFeedback'
type MockService_ProcessFeedback_Call struct {
	*mock.Call
}

// ProcessFeedback is a helper method to define mock.On call
//   - ctx context.Context
//   - req *feedback.FeedbackRequest
func (_e *MockService_Expecter) ProcessFeedback(ctx interface{}, req interface{}) *MockService_ProcessFeedback_Call {
	return &MockService_ProcessFeedback_Call{Call: _e.mock.On("ProcessFeedback", ctx, req)}
}

func (_c *MockService_ProcessFeedback_Call) Run(run func(ctx context.Context, req *feedback.FeedbackRequest)) *MockService_ProcessFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*feedback.FeedbackRequest))
	})
	return _c
}

func (_c *MockService_ProcessFeedback_Call) Return(_a0 *feedback.StrategyUpdate, _a1 error) *MockService_ProcessFeedback_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ProcessFeedback_Call) RunAndReturn(run func(context.Context, *feedback.FeedbackRequest) (*feedback.StrategyUpdate, error)) *MockService_ProcessFeedback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
